require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CourseSectionsController do

  # This should return the minimal set of attributes required to create a valid
  # CourseSection. As you add validations to CourseSection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CourseSectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all course_sections as @course_sections" do
      course_section = CourseSection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:course_sections).should eq([course_section])
    end
  end

  describe "GET show" do
    it "assigns the requested course_section as @course_section" do
      course_section = CourseSection.create! valid_attributes
      get :show, {:id => course_section.to_param}, valid_session
      assigns(:course_section).should eq(course_section)
    end
  end

  describe "GET new" do
    it "assigns a new course_section as @course_section" do
      get :new, {}, valid_session
      assigns(:course_section).should be_a_new(CourseSection)
    end
  end

  describe "GET edit" do
    it "assigns the requested course_section as @course_section" do
      course_section = CourseSection.create! valid_attributes
      get :edit, {:id => course_section.to_param}, valid_session
      assigns(:course_section).should eq(course_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CourseSection" do
        expect {
          post :create, {:course_section => valid_attributes}, valid_session
        }.to change(CourseSection, :count).by(1)
      end

      it "assigns a newly created course_section as @course_section" do
        post :create, {:course_section => valid_attributes}, valid_session
        assigns(:course_section).should be_a(CourseSection)
        assigns(:course_section).should be_persisted
      end

      it "redirects to the created course_section" do
        post :create, {:course_section => valid_attributes}, valid_session
        response.should redirect_to(CourseSection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved course_section as @course_section" do
        # Trigger the behavior that occurs when invalid params are submitted
        CourseSection.any_instance.stub(:save).and_return(false)
        post :create, {:course_section => {  }}, valid_session
        assigns(:course_section).should be_a_new(CourseSection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CourseSection.any_instance.stub(:save).and_return(false)
        post :create, {:course_section => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested course_section" do
        course_section = CourseSection.create! valid_attributes
        # Assuming there are no other course_sections in the database, this
        # specifies that the CourseSection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CourseSection.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => course_section.to_param, :course_section => { "these" => "params" }}, valid_session
      end

      it "assigns the requested course_section as @course_section" do
        course_section = CourseSection.create! valid_attributes
        put :update, {:id => course_section.to_param, :course_section => valid_attributes}, valid_session
        assigns(:course_section).should eq(course_section)
      end

      it "redirects to the course_section" do
        course_section = CourseSection.create! valid_attributes
        put :update, {:id => course_section.to_param, :course_section => valid_attributes}, valid_session
        response.should redirect_to(course_section)
      end
    end

    describe "with invalid params" do
      it "assigns the course_section as @course_section" do
        course_section = CourseSection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CourseSection.any_instance.stub(:save).and_return(false)
        put :update, {:id => course_section.to_param, :course_section => {  }}, valid_session
        assigns(:course_section).should eq(course_section)
      end

      it "re-renders the 'edit' template" do
        course_section = CourseSection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CourseSection.any_instance.stub(:save).and_return(false)
        put :update, {:id => course_section.to_param, :course_section => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested course_section" do
      course_section = CourseSection.create! valid_attributes
      expect {
        delete :destroy, {:id => course_section.to_param}, valid_session
      }.to change(CourseSection, :count).by(-1)
    end

    it "redirects to the course_sections list" do
      course_section = CourseSection.create! valid_attributes
      delete :destroy, {:id => course_section.to_param}, valid_session
      response.should redirect_to(course_sections_url)
    end
  end

end
